### ISSUE TITLE
reports itself as 1.6, tries to update, then freezes

### ISSUE THREAD

**Issue by twinec** [LyfeOnEdge/unofficial-appstore#2]
I downloaded 1.7, opened it (hardest thing to do) and it said it needed an update, i said sure, it updated, then stopped responding. what should I do? What did I do wrong?
EDIT: I downloaded it straight from the Master, and it worked. update your version AFTER you update the file, you idgit

**Comment by LyfeOnEdge** [comment]
Fixed it, thanks for the bug report!
